In [2]:
!pip install numpy
import numpy



In [9]:
y = numpy.array( [[(1,2),(5,6)]], numpy.int32)
# Guardando enteros de 32 bit

X = numpy.array(['hola','hola', '1'])

X


array(['hola', 'hola', '1'], dtype='<U4')

In [10]:
y.dtype

dtype('int32')

In [11]:
y.shape

(1, 2, 2)

In [12]:
print(X)

['hola' 'hola' '1']


In [24]:
y = numpy.array([[1,2,3],[4,5,6]])

y.dtype

dtype('int32')

In [22]:
y[1,:2]

array([4, 5])

In [27]:
y = numpy.array([[1,2,3],[4,5,6]])

y.dtype


dtype('int32')

In [30]:
y = numpy.array([[1,2.0,3],[4,5,6]])

y.dtype


dtype('float64')

In [31]:
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]


In [44]:
# Extraction of elements

y[0,:2]

array([1., 2.])

In [33]:
# Extraction of elements


y[1,:2]

array([4., 5.])

In [38]:
# Extraction of elements


y[1,:3]

array([4., 5., 6.])

In [39]:
print(y)


[[1. 2. 3.]
 [4. 5. 6.]]


In [43]:
#To make a copy ([row,column])

a = y [:,1].copy()
print(a)

[2. 5.]


In [47]:
# Reassign value

y[0]=20
print(y)


[[20. 20. 20.]
 [ 4.  5.  6.]]


In [52]:
# Taking specific elements from the copy

y[0:3,0:3]

array([[20., 20., 20.],
       [ 4.,  5.,  6.]])

In [53]:
# Taking specific elements from the copy

y[0:2,0:2]

array([[20., 20.],
       [ 4.,  5.]])

In [55]:
# Taking specific elements from the copy

y[0:1,0:1]

array([[20.]])

In [60]:
# Taking specific elements from the copy

y[1:2,0:1]


array([[4.]])

In [62]:
print(y)

[[20. 20. 20.]
 [ 4.  5.  6.]]


In [64]:
# Taking specific elements from the copy

y[:1,0:1]


array([[20.]])

In [66]:
# Taking specific elements from the copy

y[:2,:2]


array([[20., 20.],
       [ 4.,  5.]])

In [77]:
# Taking specific elements from the copy
# ???

y[1:2,2:3]


array([[6.]])